version: "3.9"
services:

  metrics-agent:
    build:
      context: "../"
      dockerfile: "docker/DockerfileTxAgent"
    container_name: tx-agent
    depends_on:
      - nodus-db
    restart: no
    networks:
      - net

  nodus-db:
    image: postgres:latest
    container_name: nodus-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - net

networks:
  net: